class entrypoint{
      public static void main(String [] args){
	      // WHEN YOU COMPILE AND RUN THIS PROGRAM , IT WONT SHOW ANY ERRORS AS THERE ARE NO ERRORS
	      // BUT THIS PORGRAM WILL NOT PRINT/DISPLAY ANYTHING ON THE TERMINAL AFTER RUNNING
      }
}
